### ISSUE TITLE
Text in settings options cannot be visualized

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#391]
From user feedback.

**Description of the problem:**

Test signatures > Settings > Options > Signature type: Hallmark >The Hallmark genesets text will colide with page border and not be shown. 

<img width="481" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/1c417490-e56d-44f0-9845-528d2ff7ef83">

**Possible fix:**
Trim text, use tooltips or collapse the text.

**Comment by mauromiguelm** [comment]
This was working sometime ago, if I remember correct, text would collapse. What was the reason that we stopped doing it? Purely aesthetic or to fix some other issue?

I am afraid we will fix this and break some other thing that was fixed to correct it...

**Comment by ivokwee** [comment]
I checked with an example, it is because many geneset names don't have space and don't break. So we must replace the  underscore with a space. But we must be careful that geneset name are equal to those in other places like the GMT object and original genesets. The selectInput choices can be named, so the visible name is with space but the selected values are still underscored. So fix is to name the choice vector with spaces, additionally we can remove prefix.
 
![image](https://github.com/bigomics/omicsplayground/assets/19613146/2cfc19d4-a305-44cf-aec6-7833c35a4660)

**Comment by ivokwee** [comment]
Original bug report from Dana Mitchell: "In the Signatures tab, under Test signatures > settings, the font is so big and the window cannot be adjusted to an appropriate size that you cannot see the full name of the signatures from the drop down menu. For example: it says Hallmark: KRAS...... and I can't see if it is up or down etc. This is probably even more annoying because of what a nightmare it has been just to log into the program since the new update. "

**Comment by ivokwee** [comment]
Done. See image. named the choice vector, removed prefix, and put to lowercase.

![image](https://github.com/bigomics/omicsplayground/assets/19613146/50f9d8ff-e8ca-481e-bd59-acad294dad7a)

**Comment by ivokwee** [comment]
Need to check if this happens in other selectInput widgets. Closing.

**Comment by mauromiguelm** [comment]
reopening, in RC18 its still not fixed

<img width="1280" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/d8a358a5-7b3f-49f4-b667-43b0f3ce8d35">

@ESCRI11 you had a solution once, what happened to it? Could you post that link here, so we can follow up on this?

**Comment by mauromiguelm** [comment]
reopening, in RC18 its still not fixed

<img width="1280" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/d8a358a5-7b3f-49f4-b667-43b0f3ce8d35">

@ESCRI11 you had a solution once, what happened to it? Could you post that link here, so we can follow up on this?

**Comment by ESCRI11** [comment]
RC21 (latest OPG master), latest `bigdash` and `playbase` work as expected.
![image](https://github.com/bigomics/omicsplayground/assets/10220503/c19b82a5-29f0-475d-b1d5-3ed98c882726)
Please confirm on your end and close the issue if solved.

**Comment by mauromiguelm** [comment]
I have latest bigdash and playbase and I get the problem
<img width="1136" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/a1e722a7-e05e-40fb-aaef-bd6cf85fb2c2">
