### ISSUE TITLE
V3 does not start from Docker

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#538]
Hi,

I just updated my docker to the latest version of the platform (image ID: 7caea4b42406) and it keeps exiting after a second or two from starting. I have tried several times but with the same result. Docker is also updated to the latest version.

![image](https://github.com/bigomics/omicsplayground/assets/85561624/c9c413c0-ae66-4011-b368-e8eb8e36e7af)

**Comment by ivokwee** [comment]
yes there is some problem with packages in the latest docker. it should have been resolved by now. closing issue.

**Comment by AxelBigOmics** [comment]
I'm sorry to report that after updating to the latest version of the docker image this morning (03.07.23), the same error persists,
