### ISSUE TITLE
URGENT: Gene and geneset signature plots not displaying in current version (v3.2.35-stable231129)

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#774]
Doing a training session with a customer on the cloud-based version, we both noticed that the gen and geneset signature plots where not being displayed, regardless of the dataset we were using:

![Screenshot 2023-11-30 211650](https://github.com/bigomics/omicsplayground/assets/85561624/81bcaa54-c5db-4131-8a24-639427c70224)

On top of that, we were unable to selected a phenotype (under "Show Phenotype), which remained blank.

**Comment by mauromiguelm** [comment]
I confirm the issue in the version stable v3.2.35.
<img width="1277" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/d1dfa210-d995-4034-b21a-e78a7a476415">


However, this is fine in master (multi-species), which is based on v3.2.34. That means the issue is on v3.2.35. Should we fix in stable or v3.2.35? The problem is that it will conflict with master, which is woring (see below) @ivokwee 
<img width="1253" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/0de3caeb-f84b-4dfa-a6a8-b46d9d17a302">

**Comment by ivokwee** [comment]
OK. Fixed in v3.2.38 stable branch.  Added list() for multiple reactives in observeEvent. See commit  a7a0b3870a0e885f17e9aed0a598ad0636fce1f9

**Comment by AxelBigOmics** [comment]
Unfortunately this issue is still present in v3.2.38-stable231205

**Comment by phisanti** [comment]
I reopen this issue and I will try to fix it this week
